# Copyright (c) 2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

# A GitHub workflow using CMake, Ninja and vcpkg.
# It is called "pure" because it is an example which minimizes the usage of custom GitHub actions, but leverages directly the tools that could be easily run on your development machines (i.e. CMake, vcpkg, Ninja).
name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src_repo

      - uses: microsoft/setup-msbuild@v1.1

      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Download ScyllaHide
        run: ./tools/setup-scylla.ps1
        shell: pwsh
        working-directory: "${{ github.workspace }}/src_repo"

      - name: Build
        run: |
          cmake -S "${{ github.workspace }}/src_repo" -B "${{ env.CMAKE_BUILD_DIR }}" `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
            -DMODENGINE_DIST_SCYLLA=1 `
            -DCPACK_GENERATOR=ZIP `
            -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: modengine-build
          path: ${{ env.CMAKE_BUILD_DIR }}/*.zip
